version: "3.8"

services:
  db:
    image: mysql
    container_name: mysql_next
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: strapi
      MYSQL_DATABASE: strapi
    networks:
      - nextapi

  api:
    image: strapi/strapi # Here the image of the API
    container_name: api
    restart: always
    environment:
      NODE_ENV: production
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    networks:
      - nextapi
      - client
    ports:
      - 8080:1337
    volumes:
     - app:/srv/app
    depends_on:
      - db
    command: 
      - /bin/bash
      - -c
      - |
        strapi build
        strapi start

  client:
    image: falia/next-recipe-app:client # Here the image of the client
    container_name: client
    restart: always
    environment:
      API_URL: api
    networks:
      - client
      - nextapi
    ports:
      - 8070:8080
    depends_on:
      - api

networks:
  client:
  nextapi:

volumes:
  app: