version: "3"

services:
  strapi:
    image: strapi/strapi
    environment:
      NODE_ENV: production
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: 'false'
    volumes:
      - ./api:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - mysql
    networks:
      - nextapi
      - client

  mysql:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: strapi
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
    networks:
      - nextapi

  client:
    image: falia/next-recipe-app:client # Here the image of the client
    container_name: client
    restart: always
    environment:
      API_URL: http://strapi:1337
      #NODE_TLS_REJECT_UNAUTHORIZED: "0"
    networks:
      - client
    ports:
      - 8070:8080
    depends_on:
      - strapi

networks:
  client:
  nextapi: